# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import environment_pb2 as environment__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in environment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnvironmentManagerServiceStub:
    """Defines the gRPC service for managing execution environments
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEnvironments = channel.unary_unary(
                '/environment.EnvironmentManagerService/ListEnvironments',
                request_serializer=environment__pb2.ListEnvironmentsRequest.SerializeToString,
                response_deserializer=environment__pb2.ListEnvironmentsResponse.FromString,
                _registered_method=True)
        self.GetEnvironment = channel.unary_unary(
                '/environment.EnvironmentManagerService/GetEnvironment',
                request_serializer=environment__pb2.GetEnvironmentRequest.SerializeToString,
                response_deserializer=environment__pb2.EnvironmentDetail.FromString,
                _registered_method=True)
        self.CreateEnvironment = channel.unary_unary(
                '/environment.EnvironmentManagerService/CreateEnvironment',
                request_serializer=environment__pb2.CreateEnvironmentRequest.SerializeToString,
                response_deserializer=environment__pb2.EnvironmentDetail.FromString,
                _registered_method=True)
        self.UpdateEnvironment = channel.unary_unary(
                '/environment.EnvironmentManagerService/UpdateEnvironment',
                request_serializer=environment__pb2.UpdateEnvironmentRequest.SerializeToString,
                response_deserializer=environment__pb2.EnvironmentDetail.FromString,
                _registered_method=True)
        self.DeleteEnvironment = channel.unary_unary(
                '/environment.EnvironmentManagerService/DeleteEnvironment',
                request_serializer=environment__pb2.DeleteEnvironmentRequest.SerializeToString,
                response_deserializer=environment__pb2.DeleteEnvironmentResponse.FromString,
                _registered_method=True)


class EnvironmentManagerServiceServicer:
    """Defines the gRPC service for managing execution environments
    """

    def ListEnvironments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvironmentManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListEnvironments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEnvironments,
                    request_deserializer=environment__pb2.ListEnvironmentsRequest.FromString,
                    response_serializer=environment__pb2.ListEnvironmentsResponse.SerializeToString,
            ),
            'GetEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnvironment,
                    request_deserializer=environment__pb2.GetEnvironmentRequest.FromString,
                    response_serializer=environment__pb2.EnvironmentDetail.SerializeToString,
            ),
            'CreateEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEnvironment,
                    request_deserializer=environment__pb2.CreateEnvironmentRequest.FromString,
                    response_serializer=environment__pb2.EnvironmentDetail.SerializeToString,
            ),
            'UpdateEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEnvironment,
                    request_deserializer=environment__pb2.UpdateEnvironmentRequest.FromString,
                    response_serializer=environment__pb2.EnvironmentDetail.SerializeToString,
            ),
            'DeleteEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEnvironment,
                    request_deserializer=environment__pb2.DeleteEnvironmentRequest.FromString,
                    response_serializer=environment__pb2.DeleteEnvironmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'environment.EnvironmentManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('environment.EnvironmentManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnvironmentManagerService:
    """Defines the gRPC service for managing execution environments
    """

    @staticmethod
    def ListEnvironments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment.EnvironmentManagerService/ListEnvironments',
            environment__pb2.ListEnvironmentsRequest.SerializeToString,
            environment__pb2.ListEnvironmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment.EnvironmentManagerService/GetEnvironment',
            environment__pb2.GetEnvironmentRequest.SerializeToString,
            environment__pb2.EnvironmentDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment.EnvironmentManagerService/CreateEnvironment',
            environment__pb2.CreateEnvironmentRequest.SerializeToString,
            environment__pb2.EnvironmentDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment.EnvironmentManagerService/UpdateEnvironment',
            environment__pb2.UpdateEnvironmentRequest.SerializeToString,
            environment__pb2.EnvironmentDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment.EnvironmentManagerService/DeleteEnvironment',
            environment__pb2.DeleteEnvironmentRequest.SerializeToString,
            environment__pb2.DeleteEnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
