# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import process_pb2 as process__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in process_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProcessManagerServiceStub:
    """Defines the gRPC service for managing AI processes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProcesses = channel.unary_unary(
                '/process.ProcessManagerService/ListProcesses',
                request_serializer=process__pb2.ListProcessesRequest.SerializeToString,
                response_deserializer=process__pb2.ListProcessesResponse.FromString,
                _registered_method=True)
        self.GetProcess = channel.unary_unary(
                '/process.ProcessManagerService/GetProcess',
                request_serializer=process__pb2.GetProcessRequest.SerializeToString,
                response_deserializer=process__pb2.ProcessDetail.FromString,
                _registered_method=True)
        self.CreateProcess = channel.unary_unary(
                '/process.ProcessManagerService/CreateProcess',
                request_serializer=process__pb2.CreateProcessRequest.SerializeToString,
                response_deserializer=process__pb2.ProcessDetail.FromString,
                _registered_method=True)
        self.UpdateProcess = channel.unary_unary(
                '/process.ProcessManagerService/UpdateProcess',
                request_serializer=process__pb2.UpdateProcessRequest.SerializeToString,
                response_deserializer=process__pb2.ProcessDetail.FromString,
                _registered_method=True)
        self.DeleteProcess = channel.unary_unary(
                '/process.ProcessManagerService/DeleteProcess',
                request_serializer=process__pb2.DeleteProcessRequest.SerializeToString,
                response_deserializer=process__pb2.DeleteProcessResponse.FromString,
                _registered_method=True)
        self.StartProcess = channel.unary_unary(
                '/process.ProcessManagerService/StartProcess',
                request_serializer=process__pb2.StartProcessRequest.SerializeToString,
                response_deserializer=process__pb2.ProcessStatusResponse.FromString,
                _registered_method=True)
        self.StopProcess = channel.unary_unary(
                '/process.ProcessManagerService/StopProcess',
                request_serializer=process__pb2.StopProcessRequest.SerializeToString,
                response_deserializer=process__pb2.ProcessStatusResponse.FromString,
                _registered_method=True)
        self.PullProcess = channel.unary_unary(
                '/process.ProcessManagerService/PullProcess',
                request_serializer=process__pb2.PullProcessRequest.SerializeToString,
                response_deserializer=process__pb2.ProcessDetail.FromString,
                _registered_method=True)


class ProcessManagerServiceServicer:
    """Defines the gRPC service for managing AI processes
    """

    def ListProcesses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProcesses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProcesses,
                    request_deserializer=process__pb2.ListProcessesRequest.FromString,
                    response_serializer=process__pb2.ListProcessesResponse.SerializeToString,
            ),
            'GetProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcess,
                    request_deserializer=process__pb2.GetProcessRequest.FromString,
                    response_serializer=process__pb2.ProcessDetail.SerializeToString,
            ),
            'CreateProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProcess,
                    request_deserializer=process__pb2.CreateProcessRequest.FromString,
                    response_serializer=process__pb2.ProcessDetail.SerializeToString,
            ),
            'UpdateProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProcess,
                    request_deserializer=process__pb2.UpdateProcessRequest.FromString,
                    response_serializer=process__pb2.ProcessDetail.SerializeToString,
            ),
            'DeleteProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProcess,
                    request_deserializer=process__pb2.DeleteProcessRequest.FromString,
                    response_serializer=process__pb2.DeleteProcessResponse.SerializeToString,
            ),
            'StartProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.StartProcess,
                    request_deserializer=process__pb2.StartProcessRequest.FromString,
                    response_serializer=process__pb2.ProcessStatusResponse.SerializeToString,
            ),
            'StopProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.StopProcess,
                    request_deserializer=process__pb2.StopProcessRequest.FromString,
                    response_serializer=process__pb2.ProcessStatusResponse.SerializeToString,
            ),
            'PullProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.PullProcess,
                    request_deserializer=process__pb2.PullProcessRequest.FromString,
                    response_serializer=process__pb2.ProcessDetail.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'process.ProcessManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('process.ProcessManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProcessManagerService:
    """Defines the gRPC service for managing AI processes
    """

    @staticmethod
    def ListProcesses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/process.ProcessManagerService/ListProcesses',
            process__pb2.ListProcessesRequest.SerializeToString,
            process__pb2.ListProcessesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/process.ProcessManagerService/GetProcess',
            process__pb2.GetProcessRequest.SerializeToString,
            process__pb2.ProcessDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/process.ProcessManagerService/CreateProcess',
            process__pb2.CreateProcessRequest.SerializeToString,
            process__pb2.ProcessDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/process.ProcessManagerService/UpdateProcess',
            process__pb2.UpdateProcessRequest.SerializeToString,
            process__pb2.ProcessDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/process.ProcessManagerService/DeleteProcess',
            process__pb2.DeleteProcessRequest.SerializeToString,
            process__pb2.DeleteProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/process.ProcessManagerService/StartProcess',
            process__pb2.StartProcessRequest.SerializeToString,
            process__pb2.ProcessStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/process.ProcessManagerService/StopProcess',
            process__pb2.StopProcessRequest.SerializeToString,
            process__pb2.ProcessStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/process.ProcessManagerService/PullProcess',
            process__pb2.PullProcessRequest.SerializeToString,
            process__pb2.ProcessDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
