# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sandbox_pb2 as sandbox__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxServiceStub:
    """Defines the gRPC service for managing and interacting with sandboxes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Provision = channel.unary_unary(
                '/sandbox.SandboxService/Provision',
                request_serializer=sandbox__pb2.ProvisionRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ProvisionResponse.FromString,
                _registered_method=True)
        self.Teardown = channel.unary_unary(
                '/sandbox.SandboxService/Teardown',
                request_serializer=sandbox__pb2.TeardownRequest.SerializeToString,
                response_deserializer=sandbox__pb2.TeardownResponse.FromString,
                _registered_method=True)
        self.TerminalStream = channel.stream_stream(
                '/sandbox.SandboxService/TerminalStream',
                request_serializer=sandbox__pb2.TerminalInput.SerializeToString,
                response_deserializer=sandbox__pb2.TerminalOutput.FromString,
                _registered_method=True)


class SandboxServiceServicer:
    """Defines the gRPC service for managing and interacting with sandboxes
    """

    def Provision(self, request, context):
        """Provision a new sandbox (local, docker, ssh)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Teardown(self, request, context):
        """Teardown a sandbox
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminalStream(self, request_iterator, context):
        """Bidirectional stream for terminal interactions (stdin, stdout, stderr)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Provision': grpc.unary_unary_rpc_method_handler(
                    servicer.Provision,
                    request_deserializer=sandbox__pb2.ProvisionRequest.FromString,
                    response_serializer=sandbox__pb2.ProvisionResponse.SerializeToString,
            ),
            'Teardown': grpc.unary_unary_rpc_method_handler(
                    servicer.Teardown,
                    request_deserializer=sandbox__pb2.TeardownRequest.FromString,
                    response_serializer=sandbox__pb2.TeardownResponse.SerializeToString,
            ),
            'TerminalStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TerminalStream,
                    request_deserializer=sandbox__pb2.TerminalInput.FromString,
                    response_serializer=sandbox__pb2.TerminalOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sandbox.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sandbox.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService:
    """Defines the gRPC service for managing and interacting with sandboxes
    """

    @staticmethod
    def Provision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/Provision',
            sandbox__pb2.ProvisionRequest.SerializeToString,
            sandbox__pb2.ProvisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Teardown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/Teardown',
            sandbox__pb2.TeardownRequest.SerializeToString,
            sandbox__pb2.TeardownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminalStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sandbox.SandboxService/TerminalStream',
            sandbox__pb2.TerminalInput.SerializeToString,
            sandbox__pb2.TerminalOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
